AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/ct05-cloudformation-artifacts/b53e2d5873b78a2b84413b4edcf183ce.template
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDBStack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/ct05-cloudformation-artifacts/f34ad18e0fae36915898a81758899445.template
  LambdaStack1:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMRolesStack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/ct05-cloudformation-artifacts/146653145c9c3e65711ad14058576ccd.template
      Parameters:
        LambdaExecutionRoleArn:
          Fn::GetAtt:
          - IAMRolesStack
          - Outputs.LambdaExecutionRoleArn
  LambdaStack2:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMRolesStack
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/ct05-cloudformation-artifacts/7a4978a51d0155aa7e42c91ed1c8bd32.template
      Parameters:
        LambdaExecutionRoleArn:
          Fn::GetAtt:
          - IAMRolesStack
          - Outputs.LambdaExecutionRoleArn
  LexBotStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - LambdaStack1
    - LambdaStack2
    Properties:
      TemplateURL: 
        https://s3.ap-south-1.amazonaws.com/ct05-cloudformation-artifacts/c857d2e30e2ac84c57b19012fe0154a5.template
